sudo: false

language: rust
rust:
  - 1.28.0  # minimum version, support for system allocator
  - stable
  - nightly

cache: cargo

script:
  - cargo check --verbose --all

notifications:
  email:
on_success: never
