[package]
name = "timeplot"
version = "0.3.0"
authors = ["Vasya Novikov <n1dr+cm3513git@ya.ru>"]

[dependencies]
gnuplot = "0.0.26"
#log = "0.4"
#env_logger = "0.5.13"
#rusqlite="0.10.0"
#regex = "0.2"


[profile.release]
lto = true
