[package]
name = "timeplot"
version = "0.7.2"
description = "Personal activity tracker & graph plotter"
authors = ["Vasya Novikov <n1dr+cm3513git@ya.ru>"]
license="GPL-3.0-or-later"
keywords = ["graph", "plot", "time", "tracker", "logger"]
repository = "https://github.com/vn971/timeplot"
readme = "README.md"


[dependencies]
chrono = "0.4"
fs2 = "0.4.3"
gnuplot = "0.0.26"
directories = "1.0"
open = "*"

[dependencies.config]
version = "0.9"
default-features = false
features = ["toml"]

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser"] }
user32-sys = "0.2.0"


[profile.release]
lto = true
