[main]
plot_days=7.0
sleep_minutes=3.0  # how much to wait for next iteration (ideally 60-600 sec)


[graph]
extension="svg"
show_stats=true
show_day_labels=true
size=""  # example: "1200 400" or "" (default)
height_scale=10.0  #default 1.0


[category.work]
color="black"

[category.personal]
color="orange"

[category.fun]
color="red"
# example command. Lock screen if it's too late or too early.
# it's best to move complex functionality to a script of course.
command=["sh", "-c", "(test $(date '+%k') -ge 22) || test $(date '+%k') -le 11 && xscreensaver-command -lock || true"]


# All categories are logged, but only the one listed here are being plotted.
# If you add categories later, old logged entries will be re-analyzed and re-drawn.
